// <auto-generated />
using System;
using Bokbutiken.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bokbutiken.Migrations
{
    [DbContext(typeof(BokDbContext))]
    partial class BokDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Bokbutiken.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Instock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBookOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1,
                            ImageUrl = "Pride_and_prejudice.jpg",
                            Instock = true,
                            IsBookOfTheWeek = true,
                            LongDescription = "Pride and Prejudice, which opens with one of the most famous sentences in English Literature, is an ironic novel of manners.In it the garrulous and emptyheaded Mrs Bennet has only one aim - that of finding a good match for each of her five daughters.In this she is mocked by her cynical and indolent husband. With its wit, its social precision and, above all, its irresistible heroine, Pride and Prejudice has proved one of the most enduringly popular novels in the English language. ",
                            Name = "Pride and prejudice",
                            Price = 170.99m,
                            ShortDescription = "Jane Austin",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1,
                            ImageUrl = "The_Outsider.jpg",
                            Instock = true,
                            IsBookOfTheWeek = true,
                            LongDescription = "In The Outsider (1942), his classic existentialist novel, Camus explores thealienation of an individual who refuses to conform to social norms.Meursault, his anti - hero, will not lie.When his mother dies, he refuses to show his emotions simply to satisfy the expectations of others.And when he commits a random act of violence on a sun - drenched beach near Algiers, his lack of remorse compounds his guilt in the eyes of society and the law.Yet he is as much a victim as a criminal.",
                            Name = "The Outsider",
                            Price = 199.99m,
                            ShortDescription = "Albert Camus",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1,
                            ImageUrl = "Picture_of_dorian_gray.jpg",
                            Instock = true,
                            IsBookOfTheWeek = true,
                            LongDescription = "The Picture of Dorian Gray is the only published book written by Oscar Wilde. It was first published in Lippincott's Monthly Magazine on June 20, 1890. Later, Wilde was asked to edit this version, and it was published again in April 1891.[1] The story is often incorrectly called The Portrait of Dorian Gray.",
                            Name = "The picture of Dorian Gray",
                            Price = 149.994m,
                            ShortDescription = "Oscar Wilde",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 3,
                            ImageUrl = "Orlando.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "His longing for passion, adventure and fulfilment takes him out of his own time. Chasing a dream through the centuries, he bounds from Elizabethan England and imperial Turkey to the modern world.Will he find happiness with the exotic Russian Princess Sasha ? Or is the dashing explorer Shelmerdine the ideal man ? And what form will Orlando take on the journey - a nobleman, traveller, writer? Man or... woman?",
                            Name = "Orlando",
                            Price = 249.99m,
                            ShortDescription = "Virginia Woolf",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 2,
                            ImageUrl = "Naked_lunch.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Nightmarish and fiercely funny, William Burroughs' virtuoso, taboo-breaking masterpiece Naked Lunch follows Bill Lee through Interzone: a surreal, orgiastic wasteland of drugs, depravity, political plots, paranoia, sadistic medical experiments and endless, gnawing addiction.One of the most shocking novels ever written, Naked Lunch is a cultural landmark, now in a restored edition incorporating Burroughs' notes on the text, alternate drafts and outtakes from the original.",
                            Name = "Naked Lunch",
                            Price = 176.49m,
                            ShortDescription = "William S. Burroughs",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 1,
                            ImageUrl = "Les_miserables.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Victor Hugo's tale of injustice, heroism and love follows the fortunes of Jean Valjean, an escaped convict determined to put his criminal past behind him. But his attempts to become a respected member of the community are constantly put under threat: by his own conscience, when, owing to a case of mistaken identity, another man is arrested in his place; and by the relentless investigations of the dogged Inspector Javert. It is not simply for himself that Valjean must stay free, however, for he has sworn to protect the baby daughter of Fantine, driven to prostitution by poverty.",
                            Name = "Les Miserables",
                            Price = 399.99m,
                            ShortDescription = "Victor Hugo",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 2,
                            ImageUrl = "Handmaids tale.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "The Republic of Gilead offers Offred only one function: to breed. If she deviates, she will, like dissenters, be hanged at the wall or sent out to die slowly of radiation sickness.But even a repressive state cannot obliterate desire - neither Offred's nor that of the two men on which her future hangs. Brilliantly conceived and executed, this powerful evocation of twenty - first centry America gives full rein to Margaret Atwood's devastating irony, wit and  astute perception.",
                            Name = "The Handmaid’s Tale",
                            Price = 17.64m,
                            ShortDescription = "Margaret Atwood",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 1,
                            ImageUrl = "Great_Gatsby.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "The Republic of Gilead offers Offred only one function: to breed. If she deviates, she will, like dissenters, be hanged at the wall or sent out to die slowly of radiation sickness.But even a repressive state cannot obliterate desire - neither Offred's nor that of the two men on which her future hangs.Brilliantly conceived and executed, this powerful evocation of twenty - first century America gives full rein to Margaret Atwood's devastating irony, wit and astute perception.",
                            Name = "Great Gatsby",
                            Price = 99.99m,
                            ShortDescription = "Margaret Atwood",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 1,
                            ImageUrl = "Crime_and_Punishment.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Crime and Punishment is one of the greatest and most readable novels ever written.From the beginning we are locked into the frenzied consciousness of Raskolnikov who, against his better instincts, is inexorably drawn to commit a brutal double murder. From that moment on,                we share his conflicting feelings of self - loathing and pride, of contempt for and need of others, and of terrible despair and hope of redemption: and, in a remarkable transformation of the detective novel, we follow his agonised efforts to probe and confront both his own motives for, andthe consequences of, his crime.",
                            Name = "Crime and punishment",
                            Price = 349.99m,
                            ShortDescription = "Fyodor Dostovjeskij",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 3,
                            ImageUrl = "Catcher_in_the_rye.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "The brilliant, funny, meaningful novel that established J.D. Salinger as a leading voice in American literature--and that has instilled in millions of readers around the world a lifelong love of books. If you really want to hear about it, the first thing you will probably want to know is where I was born, and what my lousy childhood was like, were occupied and all before they had me, and all that David Copperfield kind of crap, but I don't feel like going into it, if you want to know the truth.",
                            Name = "The Catcher In The Rye",
                            Price = 179.99m,
                            ShortDescription = "J.D. Salinger",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 3,
                            ImageUrl = "Animal_Farm.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "When the downtrodden animals of Manor Farm overthrow their master Mr Jones and take over the farm themselves, they imagine it is the beginning of life of freedom and equality.But gradually a cunning, ruthless elite among them, masterminded by the pigs Napoleon and Snowball, starts to take control. Soon the other animals discover that they are not all as equal as they thought, with another.",
                            Name = "Animal farm",
                            Price = 249.49m,
                            ShortDescription = "George Orwell",
                            ThumbnailImageUrl = ""
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 3,
                            ImageUrl = "1984.jpg",
                            Instock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Winston Smith works for the Ministry of Truth in London, chief city of Airstrip One.Big Brother stares out from every poster, the Thought Police uncover every act of betrayal.When Winston finds love with Julia, he discovers that life does not have to be dull and deadening, and awakens to new possibilities. Winston and Julia begin to question the Party; they are drawn towards conspiracy.Yet Big Brother will not tolerate dissent - even in the mind. For those with original thoughts they invented Room 101. . .",
                            Name = "1984",
                            Price = 198.4m,
                            ShortDescription = "George Orwell",
                            ThumbnailImageUrl = ""
                        });
                });

            modelBuilder.Entity("Bokbutiken.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Science"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Nature"
                        });
                });

            modelBuilder.Entity("Bokbutiken.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Bokbutiken.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Bokbutiken.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("BookId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Bokbutiken.Models.Book", b =>
                {
                    b.HasOne("Bokbutiken.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bokbutiken.Models.OrderDetail", b =>
                {
                    b.HasOne("Bokbutiken.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bokbutiken.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bokbutiken.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Bokbutiken.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bokbutiken.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bokbutiken.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
